name: Daily Currency Rate Fetch

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7 AM UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests pyarrow

      - name: Run data fetch script
        run: |
          python scripts/fetch_from_api.py
          python scripts/clean_data.py

      - name: Commit & Push updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git commit -m "🔁 Daily data update"
          git push
