name: Fetch Exchange Rates

on:
  schedule:
    - cron: "30 14 * * *"  # 9:30 AM EST (UTC -5)
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      TEXTBELT_API_KEY: ${{ secrets.TEXTBELT_API_KEY }}
      ALERT_PHONE_NUMBER: ${{ secrets.ALERT_PHONE_NUMBER }}
      DRY_RUN_SMS: ${{ secrets.DRY_RUN_SMS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python scripts/fetch_from_api.py
